# Required
version: 2

# Build documentation with Mkdocs
mkdocs:
   configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
      - pip install mkdocs-material==9.6.16 mkdocstrings==0.30.0 mkdocstrings-python==1.16.12 mkdocs-macros-plugin==1.3.7 jinja2==3.1.6 pymdown-extensions==10.16.1 mkdocs==1.6.1 mkdocs-material-extensions==1.3.1

    post_install:
      - poetry install --with doc
