# Required
version: 2

# Build documentation with Mkdocs
mkdocs:
   configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false

    post_install:
      - poetry install --only doc

    pre_build:
      - python -c "import material, material.extensions.emoji as e; print('mkdocs-material:', getattr(material, '__version__', 'n/a')); print('emoji ext OK:', e.__name__)"
      - poetry show mkdocs-material mkdocs-material-extensions mkdocstrings mkdocstrings-python || true