site_name: Hari
repo_url: https://github.com/julioszeferino/hari
repo_name: julioszeferino/hari
edit_uri: tree/master/docs

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
  - scheme: slate
    primary: indigo
    accent: amber
      

markdown_extensions: 
  - attr_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

plugins: 
  - macros
  - mkdocstrings:
      handlers:
        python:
          paths: [hari]
          options:
            show_root_heading: true
            backlinks: tree

extra:
  commands:
    run: hari-data
