site_name: Hari
repo_url: https://github.com/julioszeferino/hari
repo_name: julioszeferino/hari
edit_uri: tree/master/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
  - scheme: slate
    primary: indigo
    accent: amber
      

markdown_extensions: 
  - attr_list

extra_css:
  - stylesheets/extra.css